<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="btkamr">

    <!-- Tahrik Teker Nitelikleri  -->

    <xacro:property name="wh_radius" value="0.1"/>
    <xacro:property name="wh_thick" value="0.04"/>
    <xacro:property name="wh_chasis_gap" value="0.001"/>
    <xacro:property name="wh_mass" value="1.0"/>



    <!-- Avare Teker Nitelikleri -->

    <xacro:property name="cwh_chasis_offset_xy" value="0.1"/>
    <!-- yarı çapı diğer niteliklere göre ayarlayalım -->
    <xacro:property name="cwh_radius" value="${(wh_radius - (chasis_len_z / 2.0 - base_chasis_offset)) / 2.0}"/>
    <xacro:property name="cwh_mass" value="0.00001"/>



    <!-- Tahrik Tekerleği Makrosu -->
    <xacro:macro name="create_wh" params="postfix yfact">

        <joint name="base_TO_wh_${postfix}" type="continuous">
            <origin xyz="0.0 ${yfact * (chasis_len_y / 2.0 + wh_thick / 2.0 + wh_chasis_gap)} 0.0" rpy="0.0 0.0 0.0"/>
            <parent link="base_link"/>
            <child link="wh_${postfix}"/>
            <axis xyz="0.0 1.0 0.0"/>
        </joint>

        <link name="wh_${postfix}">
            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="${pi / 2.0} 0.0 0.0"/>

                <mass value="${wh_mass}"/>
                <inertia 
                    ixx="${wh_mass * (3*wh_radius*wh_radius + wh_thick*wh_thick) / 12.0}"
                    iyy="${wh_mass * (3*wh_radius*wh_radius + wh_thick*wh_thick) / 12.0}"
                    izz="${wh_mass * (wh_radius*wh_radius) / 2.0}"
                    ixy="0" ixz="0" iyz="0"
                />
            </inertial>

            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="${pi / 2.0} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${wh_radius}" length="${wh_thick}"/>
                </geometry>
                <material name="gray"/>
            </visual>

            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="${pi / 2.0} 0.0 0.0"/>
                <geometry>
                    <cylinder 
                        radius="${wh_radius}" 
                        length="${wh_thick}"/>
                </geometry>
            </collision>
        </link>

    </xacro:macro>



    <!-- Tahrik Tekerlekleri Oluşturumu -->

    <xacro:create_wh postfix="l" yfact="1.0"/> <!-- sol -->
    <xacro:create_wh postfix="r" yfact="-1.0"/> <!-- sağ -->



    <!-- Avare Teker Makrosu -->

    <xacro:macro name="create_cwh" params="postfix xfact yfact">

        <!-- Yaw joint: x ekseni etrafında dönme -->
        <joint name="chasis_TO_cwh_${postfix}" type="fixed">
            <origin xyz="${xfact * (chasis_len_x / 2.0 - cwh_chasis_offset_xy)} 
                        ${yfact * (chasis_len_y / 2.0 - cwh_chasis_offset_xy)} 
                        ${-1 * (chasis_len_z / 2.0 + cwh_radius)}" rpy="0 0 0"/>
            <parent link="chasis"/>
            <child link="cwh_${postfix}"/>
        </joint>

        <!-- BALL CASTER LINK -->
        <link name="cwh_${postfix}">

            <!-- Çok hafif top (dönüşlerde robotu tutmaması için) -->
            <inertial>
                <mass value="0.01"/>
                <origin xyz="0 0 0"/>
                <inertia
                    ixx="1e-5" ixy="0" ixz="0"
                    iyy="1e-5" iyz="0"
                    izz="1e-5"/>
            </inertial>

            <!-- Görsel -->
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <sphere radius="${cwh_radius}"/>
                </geometry>
                <material name="gray"/>
                  
            </visual>

            <!-- Çarpışma ve sürtünme ayarları -->
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <sphere radius="${cwh_radius}"/>
                </geometry>
            </collision>
        </link>

        <!-- gazebo için sürtünme değerlerini azaltıyoruz -->
        <gazebo reference="cwh_${postfix}">
            <collision>
                <surface>
                    <friction>
                        <ode>
                            <mu>0.001</mu>    <!-- temel sürtünme -->
                            <mu2>0.001</mu2>  <!-- ikinci eksen sürtünmesi -->
                            <slip1>1.0</slip1>
                            <slip2>1.0</slip2>
                        </ode>
                    </friction>
                    <bounce>
                        <restitution_coefficient>0.0</restitution_coefficient>
                    </bounce>
                </surface>
            </collision>
        </gazebo>

    </xacro:macro>



    <!-- Avare Tekerlerin Kullanımı -->

    <xacro:create_cwh postfix="lf" xfact="1.0" yfact="1.0"/>
    <xacro:create_cwh postfix="lb" xfact="-1.0" yfact="1.0"/>
    <xacro:create_cwh postfix="rf" xfact="1.0" yfact="-1.0"/>
    <xacro:create_cwh postfix="rb" xfact="-1.0" yfact="-1.0"/>

</robot>