<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="btkamr">

<gazebo>
    <plugin 
        filename="gz-sim-joint-state-publisher-system"
        name="gz::sim::systems::JointStatePublisher"
    >

        <!-- Yayınlanacak topic ismi -->
        <topic>btkamr/joint_states</topic>
    </plugin>  


	<plugin
		filename="gz-sim-diff-drive-system"
		name="gz::sim::systems::DiffDrive"
	>

		<!-- Hız emirlerinin alınacağı topic -->
		<topic>btkamr/cmd_vel</topic>

		<!-- Sol teker jointi -->
		<left_joint>base_TO_wh_l</left_joint>
		
		<!-- Sağ teker jointi -->
		<right_joint>base_TO_wh_r</right_joint>

		<!-- Tahrik tekerlekleri arasındaki mesafe -->
		<!-- Bir tekerin, base_link'e olan uzaklığının iki katı -->
		<wheel_separation>${(chasis_len_y / 2.0 + wh_thick / 2.0 + wh_chasis_gap) * 2}</wheel_separation>

		<!-- Teker yarıçapı -->
		<wheel_radius>${wh_radius}</wheel_radius>

	</plugin>

	<plugin
		filename="gz-sim-odometry-publisher-system"
		name="gz::sim::systems::OdometryPublisher"
	>
		<!-- Odometry'nin yayımlanacağı topic -->
		<odom_topic>btkamr/odom</odom_topic>

		<!-- Odometry frame'in ismi -->
		<odom_frame>odom_frame</odom_frame>
		
		<!-- Odom frame'in yapışacağı frame-->
		<robot_base_frame>base_footprint</robot_base_frame>

		<!-- Yayım sıklığı -->
		<odom_publish_frequency>10</odom_publish_frequency>
	</plugin>

</gazebo>


</robot>